import { Pet } from '../types';

export const MOCK_PETS: Pet[] = [
  {
    id: '1',
    name: 'Buddy',
    species: 'Dog',
    breed: 'Golden Retriever',
    age: '2 years',
    price: 1200,
    description: 'Buddy is a friendly and energetic Golden Retriever. He loves playing fetch and is great with kids.',
    images: ['https://picsum.photos/seed/dog1/800/600'],
    sellerId: 'user1',
    sellerName: 'John Doe',
    sellerEmail: 'john@example.com',
    location: 'New York, NY',
    status: 'available',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '2',
    name: 'Whiskers',
    species: 'Cat',
    breed: 'Siamese',
    age: '1 year',
    price: 800,
    description: 'Whiskers is a beautiful Siamese cat with striking blue eyes. She is very affectionate and enjoys lounging in the sun.',
    images: ['https://picsum.photos/seed/cat1/800/600'],
    sellerId: 'user2',
    sellerName: 'Jane Smith',
    sellerEmail: 'jane@example.com',
    location: 'Los Angeles, CA',
    status: 'available',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '3',
    name: 'Goldie',
    species: 'Fish',
    breed: 'Goldfish',
    age: '6 months',
    price: 50,
    description: 'Goldie is a vibrant goldfish, perfect for a beginner aquarium. Very low maintenance and beautiful to watch.',
    images: ['https://picsum.photos/seed/fish1/800/600'],
    sellerId: 'user3',
    sellerName: 'Alice Johnson',
    sellerEmail: 'alice@example.com',
    location: 'Chicago, IL',
    status: 'available',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '4',
    name: 'Tweety',
    species: 'Bird',
    breed: 'Canary',
    age: '1 year',
    price: 150,
    description: 'Tweety is a cheerful canary with a lovely singing voice. She is healthy and active.',
    images: ['https://picsum.photos/seed/bird1/800/600'],
    sellerId: 'user4',
    sellerName: 'Bob Brown',
    sellerEmail: 'bob@example.com',
    location: 'Houston, TX',
    status: 'available',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];
