import { Pet } from '../types';

export const MOCK_PETS: Pet[] = [
  {
    id: '1',
    name: 'Buddy',
    species: 'Dog',
    breed: 'Golden Retriever',
    age: '2 years',
    price: 1200,
    description: 'Buddy is a friendly and energetic Golden Retriever. He loves playing fetch and is great with kids.',
    images: ['https://picsum.photos/seed/dog1/800/600', 'https://picsum.photos/seed/dog2/800/600'],
    sellerId: 'user1',
    sellerName: 'John Doe',
    sellerEmail: 'john@example.com',
    location: 'New York, NY',
    status: 'available',
    isOfficial: true,
    stockCount: 5,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '2',
    name: 'Whiskers',
    species: 'Cat',
    breed: 'Siamese',
    age: '1 year',
    price: 800,
    description: 'Whiskers is a beautiful Siamese cat with striking blue eyes. She is very affectionate and enjoys lounging in the sun.',
    images: ['https://picsum.photos/seed/cat1/800/600', 'https://picsum.photos/seed/cat2/800/600'],
    sellerId: 'user2',
    sellerName: 'Jane Smith',
    sellerEmail: 'jane@example.com',
    location: 'Los Angeles, CA',
    status: 'available',
    isOfficial: true,
    stockCount: 3,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '3',
    name: 'Goldie',
    species: 'Fish',
    breed: 'Goldfish',
    age: '6 months',
    price: 50,
    description: 'Goldie is a vibrant goldfish, perfect for a beginner aquarium. Very low maintenance and beautiful to watch.',
    images: ['https://picsum.photos/seed/fish1/800/600'],
    sellerId: 'user3',
    sellerName: 'Alice Johnson',
    sellerEmail: 'alice@example.com',
    location: 'Chicago, IL',
    status: 'available',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '4',
    name: 'Tweety',
    species: 'Bird',
    breed: 'Canary',
    age: '1 year',
    price: 150,
    description: 'Tweety is a cheerful canary with a lovely singing voice. She is healthy and active.',
    images: ['https://picsum.photos/seed/bird1/800/600'],
    sellerId: 'user4',
    sellerName: 'Bob Brown',
    sellerEmail: 'bob@example.com',
    location: 'Houston, TX',
    status: 'available',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '5',
    name: 'Thumper',
    species: 'Rabbit',
    breed: 'Holland Lop',
    age: '1 year',
    price: 200,
    description: 'Thumper is a sweet Holland Lop rabbit with floppy ears. He is very social and loves fresh carrots.',
    images: ['https://picsum.photos/seed/rabbit1/800/600'],
    sellerId: 'user5',
    sellerName: 'Charlie Green',
    sellerEmail: 'charlie@example.com',
    location: 'Phoenix, AZ',
    status: 'available',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '6',
    name: 'Luna',
    species: 'Dog',
    breed: 'Husky',
    age: '3 years',
    price: 1500,
    description: 'Luna is a stunning Husky with blue eyes. She is very active and needs a yard to run in.',
    images: ['https://picsum.photos/seed/husky1/800/600'],
    sellerId: 'user6',
    sellerName: 'David White',
    sellerEmail: 'david@example.com',
    location: 'Seattle, WA',
    status: 'available',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '7',
    name: 'Max',
    species: 'Dog',
    breed: 'German Shepherd',
    age: '4 years',
    price: 950,
    description: 'Max is a highly trained and loyal German Shepherd. Excellent guard dog and companion.',
    images: ['https://picsum.photos/seed/dog3/800/600'],
    sellerId: 'user7',
    sellerName: 'Emily Davis',
    sellerEmail: 'emily@example.com',
    location: 'Miami, FL',
    status: 'available',
    isOfficial: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '8',
    name: 'Bella',
    species: 'Dog',
    breed: 'Poodle',
    age: '2 years',
    price: 1100,
    description: 'Bella is a sophisticated and intelligent Poodle. She is hypoallergenic and very well-behaved.',
    images: ['https://picsum.photos/seed/dog4/800/600'],
    sellerId: 'user8',
    sellerName: 'Michael Wilson',
    sellerEmail: 'michael@example.com',
    location: 'San Francisco, CA',
    status: 'available',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '9',
    name: 'Charlie',
    species: 'Dog',
    breed: 'Bulldog',
    age: '5 years',
    price: 1300,
    description: 'Charlie is a laid-back Bulldog who loves naps and short walks. Great for apartment living.',
    images: ['https://picsum.photos/seed/dog5/800/600'],
    sellerId: 'user9',
    sellerName: 'Sarah Miller',
    sellerEmail: 'sarah@example.com',
    location: 'Boston, MA',
    status: 'available',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '10',
    name: 'Lucy',
    species: 'Dog',
    breed: 'Beagle',
    age: '1 year',
    price: 700,
    description: 'Lucy is a curious and friendly Beagle. She has a great sense of smell and loves exploring.',
    images: ['https://picsum.photos/seed/dog6/800/600'],
    sellerId: 'user10',
    sellerName: 'James Taylor',
    sellerEmail: 'james@example.com',
    location: 'Denver, CO',
    status: 'available',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '11',
    name: 'Cooper',
    species: 'Dog',
    breed: 'Rottweiler',
    age: '3 years',
    price: 1400,
    description: 'Cooper is a strong and protective Rottweiler. He is very loyal to his family.',
    images: ['https://picsum.photos/seed/dog7/800/600'],
    sellerId: 'user11',
    sellerName: 'Linda Anderson',
    sellerEmail: 'linda@example.com',
    location: 'Atlanta, GA',
    status: 'available',
    isOfficial: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '12',
    name: 'Daisy',
    species: 'Dog',
    breed: 'Dachshund',
    age: '2 years',
    price: 600,
    description: 'Daisy is a playful "wiener dog" with a big personality. She loves burrowing in blankets.',
    images: ['https://picsum.photos/seed/dog8/800/600'],
    sellerId: 'user12',
    sellerName: 'Robert Thomas',
    sellerEmail: 'robert@example.com',
    location: 'Portland, OR',
    status: 'available',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '13',
    name: 'Rocky',
    species: 'Dog',
    breed: 'Boxer',
    age: '4 years',
    price: 850,
    description: 'Rocky is an energetic and fun-loving Boxer. He is great with other dogs and kids.',
    images: ['https://picsum.photos/seed/dog9/800/600'],
    sellerId: 'user13',
    sellerName: 'Patricia Jackson',
    sellerEmail: 'patricia@example.com',
    location: 'San Diego, CA',
    status: 'available',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '14',
    name: 'Milo',
    species: 'Dog',
    breed: 'Yorkshire Terrier',
    age: '1 year',
    price: 1000,
    description: 'Milo is a tiny dog with a huge heart. He is very brave and loves being the center of attention.',
    images: ['https://picsum.photos/seed/dog10/800/600'],
    sellerId: 'user14',
    sellerName: 'Christopher White',
    sellerEmail: 'chris@example.com',
    location: 'Philadelphia, PA',
    status: 'available',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '15',
    name: 'Oliver',
    species: 'Cat',
    breed: 'Maine Coon',
    age: '3 years',
    price: 1200,
    description: 'Oliver is a gentle giant. He is one of the largest domestic cat breeds and very friendly.',
    images: ['https://picsum.photos/seed/cat3/800/600'],
    sellerId: 'user15',
    sellerName: 'Barbara Harris',
    sellerEmail: 'barbara@example.com',
    location: 'Austin, TX',
    status: 'available',
    isOfficial: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '16',
    name: 'Simba',
    species: 'Cat',
    breed: 'Persian',
    age: '2 years',
    price: 1500,
    description: 'Simba is a luxurious Persian cat with a long, beautiful coat. He requires regular grooming.',
    images: ['https://picsum.photos/seed/cat4/800/600'],
    sellerId: 'user16',
    sellerName: 'Daniel Martin',
    sellerEmail: 'daniel@example.com',
    location: 'Las Vegas, NV',
    status: 'available',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '17',
    name: 'Chloe',
    species: 'Cat',
    breed: 'Ragdoll',
    age: '1 year',
    price: 1300,
    description: 'Chloe is a docile and sweet Ragdoll. She goes limp with relaxation when picked up.',
    images: ['https://picsum.photos/seed/cat5/800/600'],
    sellerId: 'user17',
    sellerName: 'Nancy Thompson',
    sellerEmail: 'nancy@example.com',
    location: 'Charlotte, NC',
    status: 'available',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '18',
    name: 'Lola',
    species: 'Cat',
    breed: 'Bengal',
    age: '2 years',
    price: 2000,
    description: 'Lola is a wild-looking Bengal cat with beautiful spots. She is very active and intelligent.',
    images: ['https://picsum.photos/seed/cat6/800/600'],
    sellerId: 'user18',
    sellerName: 'Paul Garcia',
    sellerEmail: 'paul@example.com',
    location: 'San Jose, CA',
    status: 'available',
    isOfficial: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '19',
    name: 'Nemo',
    species: 'Fish',
    breed: 'Clownfish',
    age: '4 months',
    price: 75,
    description: 'Nemo is a bright orange Clownfish, famous for his white stripes. Great for saltwater tanks.',
    images: ['https://picsum.photos/seed/fish2/800/600'],
    sellerId: 'user19',
    sellerName: 'Mark Robinson',
    sellerEmail: 'mark@example.com',
    location: 'Orlando, FL',
    status: 'available',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '20',
    name: 'Bluey',
    species: 'Bird',
    breed: 'Budgie',
    age: '8 months',
    price: 40,
    description: 'Bluey is a small, colorful Budgie. He is very social and can learn to mimic sounds.',
    images: ['https://picsum.photos/seed/bird2/800/600'],
    sellerId: 'user20',
    sellerName: 'Kevin Clark',
    sellerEmail: 'kevin@example.com',
    location: 'Columbus, OH',
    status: 'available',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];
